import type { Metadata } from "next"
import { Montserrat } from "next/font/google"
import "../globals.css"
import { Header } from "@/layouts/header/Header"
// import { Footer } from "@/layouts/footer/Footer"
import { Locale } from "@/i18n.config"
import { useHydrateAtoms } from "jotai/utils"
import { localeAtom } from "@/atoms/dictionaryAtoms"
import { HydrationProvider } from "@/components/app/HydrationProvider"

const montserrat = Montserrat({
  weight: ["400", "500", "600"],
  subsets: ["latin"],
  display: "swap",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

type Params = Promise<{
  locale: Locale
}>

export default async function RootLayout(
  props: Readonly<{
    children: React.ReactNode
    params: Params
  }>
) {
  const params = await props.params

  return (
    <html lang={params.locale}>
      <body className={montserrat.className}>
        <HydrationProvider locale={params.locale}>
          <Header locale={params.locale} />
          {props.children}
          {/* <Footer /> */}
        </HydrationProvider>
      </body>
    </html>
  )
}
