import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import '../globals.css';
import { Header } from '@/layouts/header/Header';
// import { Footer } from "@/layouts/footer/Footer"
import { Locale } from '@/i18n.config';
import { Footer } from '@/layouts/footer/Footer';
// import { getDictionary } from '@/lib/getDictionary';

const montserrat = Montserrat({
  weight: ['300', '400', '500', '600', '700'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type Params = Promise<{
  locale: Locale;
}>;

export default async function RootLayout(
  props: Readonly<{
    children: React.ReactNode;
    params: Params;
  }>
) {
  const params = await props.params;

  // const dictionary = await getDictionary(params.locale);

  return (
    <html lang={params.locale} dir={params.locale === 'ar' ? 'rtl' : 'ltr'}>
      <body className={montserrat.className}>
        <Header />
        {props.children}
        <Footer />
      </body>
    </html>
  );
}
